### PR TITLE
fix: Improve popups & friendly dApps

### LINKED ISSUE #346: [proposal]: improve friendly dapp and popup handling
### Motivation

Current implementation is not ideal.

### Proposal

Should improve the handling inside the snap.
If time allows add support for editing and adjusting firendly dapps on dapps settings page.
Same for popups.

### PR DESCRIPTION
**Pull request by andyv09**
fixes #346.

- Created UI Service
- Toggle popups now disables/enables every single popup
- Add RPC methods for `addFriendlyDapp` and `removeFriendlyDapp`
- addFriendlyDapp adds the current origin to the list, removeFriendlyDapp removes params: {dapp: string}} from the list.
- update connector
- update docs
- update dApp
- update tests
- Add some additional popups

TODO: add masca.io to friendly dApps when updating state

### CODE REVIEW

File: packages/types/src/params.ts [hunk 1]
```diff
@@ -149,3 +149,7 @@ export type HandleAuthorizationRequestParams = {
 export type SetCeramicSessionRequestParams = {
   serializedSession: string;
 };
+
+export type RemoveFriendlyDappParams = {
+  dApp: string;
```
Comment (martines3000) [inline packages/types/src/params.ts:154]: Maybe rename this paramater to `id` or `name`

File: packages/types/src/api.ts [hunk 2]
```diff
@@ -65,4 +65,6 @@ export interface MascaApi {
   ): Promise<Result<void>>;
   setCeramicSession(serializedSession: string): Promise<Result<boolean>>;
   validateStoredCeramicSession(): Promise<Result<boolean>>;
+  addFriendlyDapp(): Promise<Result<boolean>>;
+  removeFriendlyDapp(dApp: string): Promise<Result<boolean>>;
```
Comment (martines3000) [inline packages/types/src/api.ts:69]: Maybe rename this parameter to `id` or `name`

File: packages/snap/tests/e2e/togglePopups.spec.ts [hunk 3]
```diff
@@ -0,0 +1,64 @@
...
+    await snapMock.rpcMocks.snap_manageState({
+      operation: 'update',
+      newState: getDefaultSnapState(account),
+    });
+    global.snap = snapMock;
+    global.ethereum = snapMock as unknown as MetaMaskInpageProvider;
+  });
+
+  it('should enable popups and then disable them', async () => {
+    const defaultState = getDefaultSnapState(account);
```
Comment (martines3000) [inline packages/snap/tests/e2e/togglePopups.spec.ts:24]: This is already done in `beforeAll`

File: packages/snap/tests/e2e/addFriendlyDapp.spec.ts [hunk 4]
```diff
@@ -0,0 +1,76 @@
...
+
+  beforeAll(async () => {
+    snapMock = createMockSnap();
+    global.snap = snapMock;
+    global.ethereum = snapMock as unknown as MetaMaskInpageProvider;
+  });
+
+  it('should add a friendlyDapp to the list', async () => {
+    const defaultState = getDefaultSnapState(account);
+    await snapMock.rpcMocks.snap_manageState({
```
Comment (martines3000) [inline packages/snap/tests/e2e/addFriendlyDapp.spec.ts:22]: Move this into `beforeEach`

File: packages/snap/tests/e2e/addFriendlyDapp.spec.ts [hunk 5]
```diff
@@ -0,0 +1,76 @@
...
+
+    const res2 = (await onRpcRequest({
+      origin: 'localhost2',
+      request: {
+        id: 'test-id',
+        jsonrpc: '2.0',
+        method: 'queryVCs',
+        params: {},
+      },
+    })) as Result<unknown>;
```
Comment (martines3000) [inline packages/snap/tests/e2e/addFriendlyDapp.spec.ts:70]:
```suggestion
    await onRpcRequest({
      origin: 'localhost2',
      request: {
        id: 'test-id',
        jsonrpc: '2.0',
        method: 'queryVCs',
        params: {},
      },
    });
```

File: packages/connector/src/snap.ts [hunk 6]
```diff
@@ -209,6 +209,30 @@ export async function togglePopups(this: Masca): Promise<Result<boolean>> {
...
+ * Adds origin of the current dApp to the list of friendly dApps. This will disable popups from appearing while using the dApp.
+ *
+ * @return Result<boolean> - true if the addition was successful
+ */
+export async function addFriendlyDapp(this: Masca): Promise<Result<boolean>> {
+  return sendSnapMethod({ method: 'addFriendlyDapp' }, this.snapId);
+}
+
+/**
+ * Removes origin of the current dApp from the list of friendly dApps. This will enable popups from appearing while using the dApp.
```
Comment (martines3000) [inline packages/connector/src/snap.ts:222]:
```suggestion
 * Removes origin of the current dApp from the list of friendly dApps. This will enable popups while using the dApp.
```

File: packages/snap/src/General.service.ts [hunk 7]
```diff
@@ -57,10 +67,21 @@ class GeneralService {
    *
    * @returns void
    */
-  static async removeFriendlyDapp(dapp: string): Promise<void> {
+  static async removeFriendlyDapp(args: { dApp: string }): Promise<void> {
+    const content = panel([
```
Comment (martines3000) [inline packages/snap/src/General.service.ts:71]: Maybe it would make sense to move all of the `const content = ...` into `UI.service.ts` and create methods for each confirmation:
- confirmRemoveFriendlyDapp
- confirmAddFriendlyDapp
- confirmSwitchMethods
....

I'm not completely sure about this, so its fine if we leave it like this :+1:

File: packages/snap/src/UI.service.ts [hunk 8]
```diff
@@ -0,0 +1,171 @@
...
+  store: string | string[],
+  verifiableCredential: any
+) =>
+  panel([
+    heading('Save Verifiable Credential'),
+    text('Would you like to save the following Verifiable Credential?'),
+    divider(),
+    text(`Credential:`),
+    copyable(JSON.stringify(verifiableCredential, null, 2)),
+    text(
```
Comment (martines3000) [inline packages/snap/src/UI.service.ts:89]: Maybe move this before the listed credential so the user doesn't need to scroll to see where the credential will be save.

File: packages/snap/src/Snap.service.ts [hunk 9]
```diff
@@ -339,69 +314,74 @@ class SnapService {
...
 
-    if (credentialOffer.startsWith('openid-credential-offer://')) {
-      await VeramoService.importIdentifier();
-      return [
-        await VeramoService.handleOIDCCredentialOffer({
-          credentialOfferURI: credentialOffer,
-        }),
-      ];
-    }
+    if (await UIService.snapConfirm(handleCredentialOfferContent())) {
```
Comment (martines3000) [inline packages/snap/src/Snap.service.ts:317]: Maybe better to first check if the credential offer is valid and then show a popup.
Also good to show some information in the popup

Comment (martines3000) [reply packages/snap/src/Snap.service.ts:317]: Same thing for OIDC credential offers

**Review by martines3000 — DISMISSED** [review]

**Review by martines3000 — APPROVED** [review]
